Repository codestates-seb/seb43_main_009, pull requests merged in 2023-05, with the labels that each got.

#5 [Docs]0430 _ReadMe수정
  README.md
Labels: 📃 Docs, 🖌 Design

#6 [Docs] Readme-FE Stack 수정
  README.md
Labels: 📃 Docs

#35 [BE][Feat] User 엔티티 CRUD 초기 셋팅
  .idea/workspace.xml
  server/.gradle/7.6.1/checksums/checksums.lock
  server/.gradle/7.6.1/checksums/md5-checksums.bin
  server/.gradle/7.6.1/checksums/sha1-checksums.bin
  server/.gradle/7.6.1/dependencies-accessors/dependencies-accessors.lock
  server/.gradle/7.6.1/dependencies-accessors/gc.properties
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileChanges/last-build.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/7.6.1/gc.properties
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/cache.properties
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/.gradle/vcs-1/gc.properties
  server/.idea/.gitignore
  server/.idea/.name
  server/.idea/compiler.xml
  server/.idea/gradle.xml
  server/.idea/jarRepositories.xml
  server/.idea/misc.xml
  server/.idea/modules.xml
  server/.idea/modules/seb-main-project-009.main.iml
  server/.idea/vcs.xml
  server/HELP.md
  server/build/classes/java/main/com/codestates/sebmainproject009/SebMainProject009Application.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/controller/UserController.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserPatchDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserPostDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserResponseDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/entity/User.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/mapper/UserMapper.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/mapper/UserMapperImpl.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/repository/UserRepository.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/service/UserService.class
  server/build/classes/java/test/com/codestates/sebmainproject009/SebMainProject009ApplicationTests.class
  server/build/generated/sources/annotationProcessor/java/main/com/codestates/sebmainproject009/user/mapper/UserMapperImpl.java
  server/build/resources/main/application.yml
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId2
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapper.class.uniqueId0
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapperImpl.class.uniqueId1
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapperImpl.java.uniqueId3
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/build/tmp/compileTestJava/previous-compilation-data.bin
Labels: 💻 BE, 🕹 Feat

#36 [BE] Server gradle 재설정
  .idea/compiler.xml
  .idea/workspace.xml
  server/.gradle/7.6.1/checksums/checksums.lock
  server/.gradle/7.6.1/checksums/md5-checksums.bin
  server/.gradle/7.6.1/checksums/sha1-checksums.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/.idea/.name
  server/.idea/compiler.xml
  server/.idea/gradle.xml
  server/.idea/modules.xml
  server/.idea/modules/seb-main-project-009.main.iml
  server/build/classes/java/main/com/codestates/sebmainproject009/SebMainProject009Application.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/controller/UserController.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserPatchDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserPostDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/dto/UserResponseDto.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/entity/User.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/mapper/UserMapper.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/mapper/UserMapperImpl.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/repository/UserRepository.class
  server/build/classes/java/main/com/codestates/sebmainproject009/user/service/UserService.class
  server/build/classes/java/test/com/codestates/sebmainproject009/SebMainProject009ApplicationTests.class
  server/build/generated/sources/annotationProcessor/java/main/com/codestates/sebmainproject009/user/mapper/UserMapperImpl.java
  server/build/resources/main/application.yml
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId2
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapper.class.uniqueId0
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapperImpl.class.uniqueId1
  server/build/tmp/compileJava/compileTransaction/stash-dir/UserMapperImpl.java.uniqueId3
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/build/tmp/compileTestJava/previous-compilation-data.bin
  server/settings.gradle
  server/src/test/java/com/codestates/sebmainproject009/SebMainProject009ApplicationTests.java
Labels: 💻 BE

#40 [Feat][FE]communityWrite_axios 코드구현
  client/node_modules/.package-lock.json
  client/node_modules/deep-diff/LICENSE
  client/node_modules/deep-diff/Readme.md
  client/node_modules/deep-diff/index.es.js
  client/node_modules/deep-diff/index.js
  client/node_modules/deep-diff/package.json
  client/node_modules/deep-diff/releases/deep-diff-0.1.3.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.1.4.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.1.5.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.1.6.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.1.7.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.2.0.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.0.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.1.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.2.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.3.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.4.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.5.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.6.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.7.min.js
  client/node_modules/deep-diff/releases/deep-diff-0.3.8.min.js
  client/node_modules/deep-diff/releases/deep-diff-debug.min.js
  client/node_modules/redux-logger/LICENSE
  client/node_modules/redux-logger/README.md
  client/node_modules/redux-logger/dist/redux-logger.js
  client/node_modules/redux-logger/package.json
  client/node_modules/redux-logger/src/core.js
  client/node_modules/redux-logger/src/defaults.js
  client/node_modules/redux-logger/src/diff.js
  client/node_modules/redux-logger/src/helpers.js
  client/node_modules/redux-logger/src/index.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/common/Footer.js
  client/src/common/Layout.js
  client/src/index.js
  client/src/page/CommunityWrite.js
  client/src/redux/counterSlice.js
  client/src/redux/store.js
Labels: 💻 FE, 🕹 Feat

#46 [BE][feat] : 커뮤니티 작성
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/server.seb-main-project-009.main.iml
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/uiDesigner.xml
  .idea/workspace.xml
  server/.gradle/7.6.1/checksums/checksums.lock
  server/.gradle/7.6.1/checksums/md5-checksums.bin
  server/.gradle/7.6.1/checksums/sha1-checksums.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/.idea/misc.xml
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/comment/controller/CommentController.java
  server/src/main/java/com/codestates/sebmainproject009/comment/dto/CommentPostDto.java
  server/src/main/java/com/codestates/sebmainproject009/comment/dto/CommentResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/comment/entity/Comment.java
  server/src/main/java/com/codestates/sebmainproject009/comment/mapper/CommentMapper.java
  server/src/main/java/com/codestates/sebmainproject009/comment/repository/CommentRepository.java
  server/src/main/java/com/codestates/sebmainproject009/comment/service/CommentService.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuPatchDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuPostDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuResponsesDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/entity/Commu.java
  server/src/main/java/com/codestates/sebmainproject009/commu/mapper/CommuMapper.java
  server/src/main/java/com/codestates/sebmainproject009/commu/repository/CommuRepository.java
  server/src/main/java/com/codestates/sebmainproject009/commu/service/CommuService.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/response/MultiResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/response/PageInfo.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🕹 Feat

#50 [Feat][FE] Community CRUD 구현
  client/src/App.js
  client/src/common/Layout.js
  client/src/page/Board.js
  client/src/page/CommunityWrite.js
  client/src/redux/counterSlice.js
  client/src/redux/store.js
  client/webpack.config.js
Labels: 💻 FE, 🕹 Feat

#58 fix community
  client/node_modules/.previewjs/v20.0.7/components.json
  client/node_modules/.previewjs/v20.0.7/vite/deps/_metadata.json
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-paginate.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-paginate.js.map
  client/src/page/Commpost.js
  client/src/page/Community.js
  client/src/page/text.js
Labels: 💻 FE, 🛠 Refactor

#59 [Fix][FE] CSS구현 및 오류코드 수정
  client/data.json
  client/src/common/Header.js
  client/src/page/Commpost.js
  client/src/page/Community.js
  client/src/style/ServiceInfoStyle.js
Labels: 💻 FE, 🖌 Design, ✔ Fix

#60 [Feat][FE]CI/CD workflows 작성
  .github/workflows/deploy.yml
Labels: 💻 FE, 🕹 Feat

#62 [BE][Test] 배포 자동화 구성 테스트
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
  server/src/main/resources/bootstrap.yml
Labels: 💻 BE, 🔄 Test

#63 [FE][Feat][Design] community
  client/src/page/Commpost.js
  client/src/page/Community.js
  client/src/page/data.json
Labels: 💻 FE, 🕹 Feat, 🖌 Design

#64 [BE][Test] Security Setting 테스트
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 💻 BE, 🔄 Test

#65 [BE][Test] Security Setting 테스트
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 💻 BE, 🔄 Test

#67 [BE][Test] Security Setting 테스트
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 💻 BE, 🔄 Test

#68 [FE][Test] GitHub action test
  client/src/index.html
Labels: 💻 FE, 🔄 Test

#69 [FE][Test] GitHub action test
  .github/workflows/webpack.yml
Labels: 💻 FE, 🔄 Test

#70 [FE][Test] GitHub action test
  .github/workflows/webpack.yml
Labels: 💻 FE, 🔄 Test

#71 [FE][Test] GitHub action test
  .github/workflows/webpack.yml
Labels: 💻 FE, 🔄 Test

#74 [FE][Test] env 수정
  client/.env
Labels: 💻 FE, 🔄 Test

#75 [Fix][FE]env 수정
  client/dist/bundle.js
  client/dist/index.html
  client/package.json
  client/src/page/user/Signup.js
  client/webpack.config.js
Labels: ✔ Fix

#79 [Refactor] spring security config 수정
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 🛠 Refactor

#80 [Refactor] spring security config 수정 -2
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 🛠 Refactor

#83 [FE][Feat] Survey 객체전달기능구현
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🕹 Feat

#86 [Test][FE]board axios fixing
  client/dist/bundle.js
  client/dist/images/1.png
  client/dist/images/2.png
  client/dist/images/3.png
  client/dist/images/high.jpg
  client/dist/images/logo.png
  client/dist/index.html
  client/src/App.js
  client/src/page/community/Board.js
  client/src/page/community/CommunityWrite.js
  client/src/redux/counterSlice.js
Labels: 🔄 Test

#87 [Refactor][Test] Commu에서 /all 엔드포인트에 Commu List로
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/service/CommuService.java
Labels: 🔄 Test, 🛠 Refactor

#88 [FE][Feat] 영양제 결과페이지 기능구현
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/page/survey/SurveyStep/Step5.js
Labels: 💻 FE, 🕹 Feat

#90 [Fix][FE]댓글달기 기능 fix
  client/src/App.js
  client/src/page/community/Board.js
  client/src/redux/counterSlice.js
  client/src/style/BoardStyle.js
Labels: 💻 FE, ✔ Fix

#91 [BE][Feat] Spring Security - JWT 인증 구현
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/dto/LoginDto.java
  server/src/main/java/com/codestates/sebmainproject009/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/sebmainproject009/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/sebmainproject009/auth/userdetails/UserDetailsService.java
  server/src/main/java/com/codestates/sebmainproject009/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/sebmainproject009/auth/utils/ErrorResponder.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/service/CommuService.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/sebmainproject009/exception/ExceptionCode.java
  server/src/main/java/com/codestates/sebmainproject009/response/ErrorResponse.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/dto/UserPatchDto.java
  server/src/main/java/com/codestates/sebmainproject009/user/dto/UserPostDto.java
  server/src/main/java/com/codestates/sebmainproject009/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/repository/UserRepository.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🕹 Feat

#93 [FE][Design] Survey CSS
  client/.DS_Store
  client/node_modules/.package-lock.json
  client/node_modules/.previewjs/v20.0.7/components.json
  client/node_modules/.previewjs/v20.0.7/vite/deps/@reduxjs_toolkit.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/@reduxjs_toolkit.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/_metadata.json
  client/node_modules/.previewjs/v20.0.7/vite/deps/axios.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/axios.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-DFKQJ226.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-DFKQJ226.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-HHTTAJVL.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-HHTTAJVL.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-JKXHZMLB.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-JKXHZMLB.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-MBJVFJ4G.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-MBJVFJ4G.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-VVC5CGEN.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/chunk-VVC5CGEN.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-dom_client.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-dom_client.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-icons_go.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-icons_go.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-icons_rx.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-icons_rx.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-paginate.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-paginate.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-redux.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-redux.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-router-dom.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react-router-dom.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/react.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react_jsx-dev-runtime.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/react_jsx-dev-runtime.js.map
  client/node_modules/.previewjs/v20.0.7/vite/deps/styled-components.js
  client/node_modules/.previewjs/v20.0.7/vite/deps/styled-components.js.map
  client/public/.DS_Store
  client/public/anticonvulsants.png
  client/public/aspirin.png
  client/public/doctor.jpg
  client/public/dryskin.png
  client/public/fatigue.png
  client/public/penicillin.png
  client/public/xray.png
  client/src/common/Header.js
  client/src/page/community/Commpost.js
  client/src/page/community/Community.js
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step5.js
Labels: 💻 FE, 🖌 Design

#95 [BE][Refactor] Auth 애너테이션 변경
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
Labels: 💻 BE, 🛠 Refactor

#97 [BE][Refactor] build.gradle 수정
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 💻 BE, 🛠 Refactor

#98 [BE][Refactor] build.gradle 수정
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
Labels: 💻 BE, 🛠 Refactor

#100 [BE][Refactor] build.gradle 수정
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/userdetails/UserDetailsService.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
Labels: 💻 BE, 🛠 Refactor

#101 [BE][Refactor] build.gradle, application.yml 수정
  server/build.gradle
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#102 [BE][Refactor] build.gradle, application.yml 수정
  server/build.gradle
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#104 [Fe][Feat] search 페이지 구현
  client/public/home.png
  client/src/common/Footer.js
  client/src/common/Layout.js
  client/src/page/Home.js
  client/src/page/search/Search.js
  client/src/style/FooterStyle.js
  client/src/style/GreetingInfo.js
  client/src/style/ServiceInfoStyle.js
Labels: 💻 FE, 🕹 Feat

#108 [FE][Fix] login, signup cors error 해결
  client/src/index.html
  client/src/page/user/Login.js
  client/src/page/user/Signup.js
Labels: 💻 FE, ✔ Fix

#109 [Fix][FE]서버와 연동버그 수정완료
  client/.env.dev
  client/src/App.js
  client/src/page/community/Board.js
  client/src/redux/boardSlice.js
  client/src/redux/store.js
  client/webpack.config.js
Labels: 💻 FE, ✔ Fix

#111 [FE][Bug] url // 버그수정
  client/.env
Labels: 💻 FE, ❗ Bug, ✔ Fix

#112 [FE][Feat] 로그아웃 버튼추가
  client/src/common/AuthProvider.js
  client/src/common/Header.js
Labels: 💻 FE, 🕹 Feat

#116 [BE][Feat] OAuth(google) + JWT 구현
  .idea/misc.xml
  .idea/workspace.xml
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/comment/controller/CommentController.java
  server/src/main/java/com/codestates/sebmainproject009/comment/dto/CommentPostDto.java
  server/src/main/java/com/codestates/sebmainproject009/comment/entity/Comment.java
  server/src/main/java/com/codestates/sebmainproject009/comment/repository/CommentRepository.java
  server/src/main/java/com/codestates/sebmainproject009/comment/service/CommentService.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/entity/Commu.java
  server/src/main/java/com/codestates/sebmainproject009/commu/repository/CommuRepository.java
  server/src/main/java/com/codestates/sebmainproject009/commu/service/CommuService.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/repository/UserRepository.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🕹 Feat

#117 [BE][Feat] OAuth - Naver 로그인 구현
  .idea/compiler.xml
  .idea/modules.xml
  .idea/workspace.xml
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/file-system.probe
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/SessionUser.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/my-page.html
  server/src/main/resources/templates/receive-token.html
Labels: 💻 BE, 🕹 Feat

#118 [FE][Fix] localStorage 사용 login
  client/src/common/Header.js
  client/src/page/user/Login.js
Labels: 💻 FE, ✔ Fix

#119 [FE][Feat][Test] login Oauth test
  client/src/common/Header.js
  client/src/page/survey/Survey.js
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#120 [FE][Fix] header token 로그아웃 버그 수정
  client/src/common/Header.js
  client/src/page/user/Login.js
Labels: 💻 FE, ✔ Fix

#125 [FE][Feat] 토큰해석파일 생성
  client/src/common/AuthProvider.js
  client/src/redux/boardSlice.js
  client/src/utils/UserInfo.js
  client/src/utils/cookies.js
Labels: 💻 FE, 🕹 Feat

#126 [FE][Fix] 불필요 경로 제거
  client/src/App.js
  client/src/page/survey/Survey.js
  client/src/page/user/Login.js
Labels: 💻 FE, ✔ Fix

#127 [BE][Refactor] build.gradle, application.yml 수정
  client/.env.dev
  client/src/common/AuthProvider.js
  client/src/common/Header.js
  client/src/page/community/Board.js
  client/src/page/community/Community.js
  client/src/page/community/CommunityPost.js
  client/src/page/community/CommunityWrite.js
  client/src/page/community/dummydata.json
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step5.js
  client/src/page/user/Login.js
  client/src/redux/CommuntiySlice.js
  client/src/redux/boardSlice.js
  client/src/redux/store.js
  client/src/style/CommunityDesign.js
  client/src/style/SurveyStyle.js
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/SebMainProject009Application.java
  server/src/main/java/com/codestates/sebmainproject009/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#128 [BE][Refactor] build.gradle, application.yml 수정
  .idea/compiler.xml
  .idea/modules.xml
  .idea/workspace.xml
  client/.env.dev
  client/src/common/AuthProvider.js
  client/src/common/Header.js
  client/src/page/community/Board.js
  client/src/page/community/Community.js
  client/src/page/community/CommunityPost.js
  client/src/page/community/CommunityWrite.js
  client/src/page/community/dummydata.json
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step5.js
  client/src/page/user/Login.js
  client/src/redux/CommuntiySlice.js
  client/src/redux/boardSlice.js
  client/src/redux/store.js
  client/src/style/CommunityDesign.js
  client/src/style/SurveyStyle.js
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/file-system.probe
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/SebMainProject009Application.java
  server/src/main/java/com/codestates/sebmainproject009/auth/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/SessionUser.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/my-page.html
  server/src/main/resources/templates/receive-token.html
Labels: 💻 BE, 🛠 Refactor

#129 [FE][Fix] 커뮤니티 작성자변경 완료
  client/src/redux/boardSlice.js
  client/src/utils/UserInfo.js
Labels: 💻 FE, ✔ Fix

#130 [FE][Fix] Survey 단계 조정
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/page/survey/SurveyStep/Step5.js
  client/src/utils/UserInfo.js
Labels: 💻 FE, ✔ Fix

#131 [FE][Feat] Oauth kakaologin 추가
  client/src/page/Home.js
  client/src/page/user/KakaoLogin.js
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#132 [FE][Fix] KakaoLogin Home 위치수정
  client/src/page/Home.js
  client/src/page/user/Login.js
Labels: 💻 FE, ✔ Fix

#133 [FE][Fix] Oauth에 Naver, Google 링크 포함
  client/src/page/Home.js
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#134 [FE][Fix] App.js KakaoLogin 경로삭제
  client/src/App.js
Labels: 💻 FE, ✔ Fix

#135 [FE][Fix] token저장후 reload
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#136 [FE][Fix] reload x navigate o
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#137 [FE][Fix] reload x navigate o2
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#138 [FE][Fix] reload x navigate o3
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#139 [FE][Fix] reload x navigate o4
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#140 [BE][Feat] Search 구현
  .idea/aws.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules/server.seb-main-project-009.main.iml
  .idea/workspace.xml
  client/src/page/user/KakaoLogin.js
  server/.gradle/7.6.1/checksums/checksums.lock
  server/.gradle/7.6.1/checksums/md5-checksums.bin
  server/.gradle/7.6.1/checksums/sha1-checksums.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/exception/ExceptionCode.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/dto/ItemResponse.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🕹 Feat

#141 [FE][Feat] redux 로그인관리파일 추가
  client/src/common/Header.js
  client/src/page/user/OAuthLogin.js
  client/src/redux/authSlice.js
  client/src/redux/store.js
Labels: 💻 FE, 🕹 Feat

#142 [FE][Feat] redux 로그인관리파일 추가2
  client/src/page/Home.js
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, 🕹 Feat

#144 [FE][Fix] 경로수정
  client/src/page/Home.js
Labels: 💻 FE, ✔ Fix

#145 [FE][Feat] 일반로그인 redux적용
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#146 [FE]redux dispatch 코드 수정
  client/node_modules/.package-lock.json
  client/package-lock.json
  client/package.json
  client/src/common/Header.js
  client/src/page/community/Board.js
  client/src/redux/boardSlice.js
  client/src/style/BoardStyle.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, ✔ Fix

#147 [FE][Feat] survey 선택에 따라 결과창 나오게 수정
  client/.DS_Store
  client/data.json
  client/public/.DS_Store
  client/public/lactoferrin.png
  client/public/lutein.png
  client/public/multivitamin.png
  client/public/vitaminB1.png
  client/public/vitaminE.jpg
  client/public/vitaminE.png
  client/public/vitaminU.png
  client/src/common/Header.js
  client/src/page/community/Community.js
  client/src/page/community/CommunityPost.js
  client/src/page/community/CommunityWrite.js
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Nutrients.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/page/user/Login.js
  client/src/style/CommunityStyle.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🕹 Feat

#148 [FE][FEAT] Search결과 기능구현
  client/data.json
  client/node_modules/.bin/acorn
  client/node_modules/.bin/ansi-html
  client/node_modules/.bin/browserslist
  client/node_modules/.bin/cssesc
  client/node_modules/.bin/envinfo
  client/node_modules/.bin/eslint
  client/node_modules/.bin/eslint-config-prettier
  client/node_modules/.bin/he
  client/node_modules/.bin/html-minifier-terser
  client/node_modules/.bin/import-local-fixture
  client/node_modules/.bin/is-docker
  client/node_modules/.bin/js-yaml
  client/node_modules/.bin/jsesc
  client/node_modules/.bin/json5
  client/node_modules/.bin/loose-envify
  client/node_modules/.bin/mime
  client/node_modules/.bin/multicast-dns
  client/node_modules/.bin/nanoid
  client/node_modules/.bin/node-which
  client/node_modules/.bin/parser
  client/node_modules/.bin/prettier
  client/node_modules/.bin/regjsparser
  client/node_modules/.bin/resolve
  client/node_modules/.bin/rimraf
  client/node_modules/.bin/semver
  client/node_modules/.bin/terser
  client/node_modules/.bin/update-browserslist-db
  client/node_modules/.bin/uuid
  client/node_modules/.bin/webpack
  client/node_modules/.bin/webpack-cli
  client/node_modules/.bin/webpack-dev-server
  client/node_modules/.package-lock.json
  client/node_modules/@babel/core/node_modules/.bin/semver
  client/node_modules/@babel/helper-compilation-targets/node_modules/.bin/semver
  client/node_modules/@babel/helper-create-class-features-plugin/node_modules/.bin/semver
  client/node_modules/@babel/helper-create-regexp-features-plugin/node_modules/.bin/semver
  client/node_modules/@babel/helper-define-polyfill-provider/node_modules/.bin/semver
  client/node_modules/@babel/preset-env/node_modules/.bin/semver
  client/node_modules/babel-plugin-polyfill-corejs2/node_modules/.bin/semver
  client/node_modules/del/node_modules/.bin/rimraf
  client/node_modules/eslint-plugin-react/node_modules/.bin/resolve
  client/node_modules/eslint-plugin-react/node_modules/.bin/semver
  client/node_modules/html-loader/node_modules/.bin/html-minifier-terser
  client/node_modules/make-dir/node_modules/.bin/semver
  client/node_modules/regjsparser/node_modules/.bin/jsesc
  client/public/block.webp
  client/public/약통1.png
  client/public/약통2.png
  client/src/common/Footer.js
  client/src/page/search/Search.js
  client/src/page/search/Search2.js
  client/src/style/FooterStyle.js
Labels: 💻 FE, 🕹 Feat

#149 [FE][Fix] 2페이지전으로 보내기
  client/src/page/user/OAuthLogin.js
Labels: 💻 FE, ✔ Fix

#150 [FE][Fix] post 값 영어로 변경
  client/node_modules/.bin/acorn
  client/node_modules/.bin/ansi-html
  client/node_modules/.bin/browserslist
  client/node_modules/.bin/cssesc
  client/node_modules/.bin/envinfo
  client/node_modules/.bin/eslint
  client/node_modules/.bin/eslint-config-prettier
  client/node_modules/.bin/he
  client/node_modules/.bin/html-minifier-terser
  client/node_modules/.bin/import-local-fixture
  client/node_modules/.bin/is-docker
  client/node_modules/.bin/js-yaml
  client/node_modules/.bin/jsesc
  client/node_modules/.bin/json5
  client/node_modules/.bin/loose-envify
  client/node_modules/.bin/mime
  client/node_modules/.bin/multicast-dns
  client/node_modules/.bin/nanoid
  client/node_modules/.bin/node-which
  client/node_modules/.bin/parser
  client/node_modules/.bin/prettier
  client/node_modules/.bin/regjsparser
  client/node_modules/.bin/resolve
  client/node_modules/.bin/rimraf
  client/node_modules/.bin/semver
  client/node_modules/.bin/terser
  client/node_modules/.bin/update-browserslist-db
  client/node_modules/.bin/uuid
  client/node_modules/.bin/webpack
  client/node_modules/.bin/webpack-cli
  client/node_modules/.bin/webpack-dev-server
  client/node_modules/.package-lock.json
  client/node_modules/@babel/core/node_modules/.bin/semver
  client/node_modules/@babel/helper-compilation-targets/node_modules/.bin/semver
  client/node_modules/@babel/helper-create-class-features-plugin/node_modules/.bin/semver
  client/node_modules/@babel/helper-create-regexp-features-plugin/node_modules/.bin/semver
  client/node_modules/@babel/helper-define-polyfill-provider/node_modules/.bin/semver
  client/node_modules/@babel/preset-env/node_modules/.bin/semver
  client/node_modules/babel-plugin-polyfill-corejs2/node_modules/.bin/semver
  client/node_modules/del/node_modules/.bin/rimraf
  client/node_modules/eslint-plugin-react/node_modules/.bin/resolve
  client/node_modules/eslint-plugin-react/node_modules/.bin/semver
  client/node_modules/html-loader/node_modules/.bin/html-minifier-terser
  client/node_modules/make-dir/node_modules/.bin/semver
  client/node_modules/regjsparser/node_modules/.bin/jsesc
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
Labels: 💻 FE, ✔ Fix

#152 [BE] Branch Update
  .github/workflows/gradle.yml
  .github/workflows/webpack.yml
  .idea/aws.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules/server.seb-main-project-009.main.iml
  .idea/workspace.xml
  client/src/page/user/KakaoLogin.js
  server/.gradle/7.6.1/checksums/checksums.lock
  server/.gradle/7.6.1/checksums/md5-checksums.bin
  server/.gradle/7.6.1/checksums/sha1-checksums.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.bin
  server/.gradle/7.6.1/executionHistory/executionHistory.lock
  server/.gradle/7.6.1/fileHashes/fileHashes.bin
  server/.gradle/7.6.1/fileHashes/fileHashes.lock
  server/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/build.gradle
  server/src/main/java/com/codestates/sebmainproject009/auth/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/exception/ExceptionCode.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/dto/ItemResponse.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/resources/application.yml
Labels: 💻 BE

#153 [BE][Feat] Survey 구현
  server/src/main/java/com/codestates/sebmainproject009/survey/Dto/SurveyDto.java
  server/src/main/java/com/codestates/sebmainproject009/survey/controller/SurveyController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
Labels: 💻 BE, 🕹 Feat

#155 [BE][Refactor] Search 존재하지 않는 데이터 예외처리, 커뮤니티 자신이 작성한 글만 삭제, 수정할 수 있게 수정
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/service/CommuService.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#156 [Fe][Design] Survey버튼 디자인
  client/src/page/survey/SurveyStep/Step2.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🖌 Design

#157 [FE][Fix] 결과창 변수 영어로 고침
  client/src/page/survey/SurveyStep/Nutrients.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, ✔ Fix

#158 [BE][Refactor] Search 존재하지 않는 데이터 예외처리, 커뮤니티 자신이 작성한 글만 삭제, 수정할 수 있게 …
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/survey/controller/SurveyController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
Labels: 💻 BE, 🛠 Refactor

#159 [BE][Refactor] Search 존재하지 않는 데이터 예외처리, 커뮤니티 자신이 작성한 글만 삭제, 수정할 수 있게 …
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
Labels: 💻 BE, 🛠 Refactor

#162 [Fe][Design] SearchResult 디자인
  client/public/urbanbrush-20211015110501511817.jpg
  client/src/page/Home.js
  client/src/page/search/SearchResult.js
  client/src/style/GreetingInfo.js
  client/src/style/Search.js
Labels: 💻 FE, 🖌 Design

#164 [Fe][Fix] SearchResult 오류수정
  client/src/page/search/SearchResult.js
  client/src/style/Search.js
Labels: 💻 FE, ✔ Fix

#165 [BE][Refactor] Search 존재하지 않는 데이터 예외처리, 커뮤니티 자신이 작성한 글만 삭제, 수정할 수 있게 …
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
Labels: 💻 BE, 🛠 Refactor

#167 FE][Feat] header 위치 고정, header redux 적용
  client/src/common/Header.js
  client/src/common/Layout.js
Labels: 💻 FE, 🕹 Feat

#168 [FE][Feat] searchlist구현
  client/node_modules/.package-lock.json
  client/src/page/search/Searchlist.js
Labels: 💻 FE, 🕹 Feat

#169 [FE][Feat] searchlist 구현
  client/src/App.js
Labels: 💻 FE, 🕹 Feat

#171 [FE][Fix] Login, Signup 한글화, 경로수정
  client/src/page/user/Login.js
  client/src/page/user/OAuthLogin.js
  client/src/page/user/Signup.js
Labels: 💻 FE, ✔ Fix

#172 [BE][Feat][Refactor] Search 구현 -4
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/ItemList.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
Labels: 💻 BE, 🕹 Feat, 🛠 Refactor

#173 [FE][Feat] 로그인에 회원가입 링크 추가
  client/src/common/Header.js
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#174 [BE] main Branch Update
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/Item.java
  server/src/main/java/com/codestates/sebmainproject009/search/entity/ItemList.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
Labels: 💻 BE

#175 [FE][Design] 버튼색 변경, 결과창 이름 노출
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🖌 Design

#179 [Fix][FE]main,board,survey 수정
  client/public/write.jpg
  client/src/page/Home.js
  client/src/page/community/Board.js
  client/src/page/search/SearchMain.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/redux/boardSlice.js
  client/src/style/BoardStyle.js
  client/src/style/GreetingInfo.js
  client/src/style/Search.js
  client/src/style/SurveyStyle.js
  client/src/variables.css
Labels: 💻 FE, ✔ Fix

#180 [FE][Fix] 구매링크 새창으로 열기
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, ✔ Fix

#181 [FE][Design] 메인 컬러 변경
  client/public/logo.png
  client/src/common/Header.js
Labels: 💻 FE, 🖌 Design

#183 [FE][Feat] 페이지 이동 스크롤 초기화
  client/src/common/Header.js
  client/src/page/Home.js
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#184 "[FE][Feat] Search 기능 추가"
  client/public/로고.png
  client/src/App.js
  client/src/page/search/SearchResult.js
  client/src/page/search/Searchlist.js
  client/src/style/Search.js
Labels: 💻 FE, 🕹 Feat

#188 [FE][Feat] Survey allergy input선택지 추가
  client/src/page/survey/SurveyStep/Step3.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🕹 Feat

#189 [FE][Feat] searchlist
  client/.DS_Store
  client/public/.DS_Store
  client/public/noimg.jpg
  client/public/nosearch.png
  client/src/App.js
  client/src/page/search/SearchMain.js
  client/src/page/search/SearchResult.js
  client/src/page/search/Searchlist.js
  client/src/redux/SearchSlice.js
  client/src/style/Search.js
  client/src/style/SearchStyle.js
Labels: 💻 FE, 🕹 Feat

#191 [FE][Feat] Survey 페이지 input창 자동완성기능 추가
  client/src/common/GoogleSearch.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🕹 Feat

#193 [FE][Feat] searchresult 이동 구현
  client/public/.DS_Store
  client/src/page/search/Searchlist.js
  client/src/style/CommunityStyle.js
Labels: 💻 FE, 🕹 Feat

#194 [Fix][FE] 스크롤 제거, axios instance 추가
  client/src/App.js
  client/src/common/Header.js
  client/src/page/community/Board.js
  client/src/page/community/Community.js
  client/src/page/community/CommunityWrite.js
  client/src/page/user/Mypage.js
  client/src/redux/MypageSlice.js
  client/src/redux/store.js
  client/src/style/BoardStyle.js
  client/src/style/CommunityStyle.js
  client/src/style/MyStyle.js
  client/src/style/Search.js
  client/src/utils/axios.js
Labels: 💻 FE, ✔ Fix

#195 [FE][Design] Survey 단계 애니메이션 적용
  client/node_modules/.package-lock.json
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
  client/src/variables.css
Labels: 💻 FE, 🖌 Design

#196 [FE][Feat] 리프레쉬토큰 쿠키에 저장
  client/src/page/user/Login.js
Labels: 💻 FE, 🕹 Feat

#197 [Feat][FE]api.js 추가, 마이페이지 기능구현
  client/src/common/Header.js
  client/src/page/user/Mypage.js
  client/src/redux/MypageSlice.js
  client/src/redux/boardSlice.js
  client/src/style/MyStyle.js
  client/src/utils/api.js
  client/src/utils/axios.js
  client/src/utils/useNavigation.js
Labels: 💻 FE, 🕹 Feat

#198 [FE][Design] pagination CSS 수정
  client/src/page/search/Searchlist.js
  client/src/style/CommunityStyle.js
  client/src/style/FooterStyle.js
  client/src/style/SearchStyle.js
Labels: 💻 FE, 🖌 Design

#199 [FE][Feat]SearchResult 버튼 추가
  client/src/page/search/SearchResult.js
  client/src/style/SearchStyle.js
Labels: 💻 FE, 🕹 Feat

#200 [FE][Design] CSS 버그수정 + 버튼취소구현
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
Labels: 💻 FE, 🖌 Design

#201 [FE][Fix] Survey 버튼버그 수정
  client/src/page/Home.js
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
Labels: 💻 FE, ✔ Fix

#202 [Feat][FE]로그인 토큰만료 로그아웃 구현
  client/public/rabbit.jpg
  client/src/common/Header.js
  client/src/page/community/CommunityPost.js
  client/src/page/user/Mypage.js
  client/src/style/MyStyle.js
  client/src/style/SearchStyle.js
  client/src/utils/api.js
  client/src/variables.css
Labels: 💻 FE, 🕹 Feat

#203 [FE][Feat] input에서 엔터치면 nextStep으로 전환
  client/src/common/GoogleSearch.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
Labels: 💻 FE, 🕹 Feat

#205 [FE][Bug] 자동완성 보류, input으로 대체
  client/src/common/GoogleSearch.js
  client/src/page/survey/SurveyStep/Step3.js
Labels: 💻 FE, ❗ Bug

#208 [FE][Feat] 로그인 토큰만료 코드수정, Header 적용
  client/src/common/Header.js
  client/src/page/user/Login.js
  client/src/utils/api.js
Labels: 💻 FE, 🕹 Feat

#209 [BE][Refactor][Feat] Search 수정, Jwt access key 발급 구현
  server/src/main/java/com/codestates/sebmainproject009/auth/controller/JwtController.java
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/sebmainproject009/json/service/JSONService.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/service/SearchService.java
Labels: 💻 BE, 🕹 Feat, 🛠 Refactor

#210 [BE][Refactor][Feat] Search 수정, Jwt access key 발급 구현
  server/src/main/java/com/codestates/sebmainproject009/auth/controller/JwtController.java
  server/src/main/java/com/codestates/sebmainproject009/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/sebmainproject009/json/service/JSONService.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/search/service/SearchService.java
Labels: 💻 BE, 🕹 Feat, 🛠 Refactor

#211 [FE][Design] Footer css 수정
  client/src/common/Footer.js
  client/src/page/search/SearchResult.js
  client/src/style/FooterStyle.js
  client/src/style/SearchStyle.js
  client/src/style/ServiceInfoStyle.js
Labels: 💻 FE, 🖌 Design

#212 [FE][Feat] searchlist loading 화면 추가
  client/dummydata.json
  client/src/common/Header.js
  client/src/common/Layout.js
  client/src/page/search/Searchlist.js
  client/src/redux/SearchSlice.js
  client/src/style/CommunityStyle.js
  client/src/style/FooterStyle.js
  client/src/style/HeaderStyle.js
  client/src/style/LayoutStyle.js
  client/src/style/Search.js
  client/src/style/SearchStyle.js
Labels: 💻 FE, 🕹 Feat

#213 [BE][Refactor] CommuController 수정
  server/src/main/java/com/codestates/sebmainproject009/auth/controller/JwtController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/s3/client/CustomS3Client.java
  server/src/main/java/com/codestates/sebmainproject009/s3/utils/GenerateName.java
Labels: 💻 BE, 🛠 Refactor

#215 [FE][Docs][Design] 스타일 컴포넌트 파일 정리 및 불필요한 코드 제거
  client/public/high.jpg
  client/src/common/Header.js
  client/src/page/Home.js
  client/src/page/community/Board.js
  client/src/page/community/Community.js
  client/src/page/community/CommunityWrite.js
  client/src/page/community/dummydata.json
  client/src/page/search/SearchResult.js
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/GreetingInfo.js
  client/src/style/HeaderStyle.js
  client/src/style/SearchStyle.js
  client/src/style/SurveyStyle.js
Labels: 📃 Docs, 🕹 Feat, 🖌 Design

#219 [BE][Feat] S3 버킷에 profile image 올릴 수 있게 구현
  server/src/main/java/com/codestates/sebmainproject009/auth/controller/JwtController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/s3/client/CustomS3Client.java
  server/src/main/java/com/codestates/sebmainproject009/s3/controller/S3Controller.java
  server/src/main/java/com/codestates/sebmainproject009/s3/utils/GenerateName.java
  server/src/main/java/com/codestates/sebmainproject009/user/controller/UserController.java
  server/src/main/java/com/codestates/sebmainproject009/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
Labels: 💻 BE, 🕹 Feat

#220 [FE][Design] 모달 애니메이션 구현
  client/src/common/Header.js
  client/src/page/user/Login.js
  client/src/page/user/LoginModal.js
  client/src/page/user/Signup.js
  client/src/style/LoginStyle.js
  client/src/style/SignupStyle.js
Labels: 💻 FE, 🖌 Design

#223 [BE][Refactor] application.yml 수정
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#224 [BE][Refactor] application.yml 수정
  server/src/main/resources/application.yml
Labels: 💻 BE

#225 [BE][Refactor] application.yml 수정
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#227 [FE][Feat] 비밀번호 조건 정규식 구현
  client/public/googleLogo.png
  client/public/kakaoLogo.png
  client/public/naverLogo.png
  client/src/page/user/Login.js
  client/src/page/user/LoginModal.js
  client/src/page/user/Signup.js
  client/src/style/LoginStyle.js
  client/src/style/SignupStyle.js
Labels: 💻 FE, 🕹 Feat

#228 [FE][Design] CSS 수정
  client/src/common/GoogleSearch.js
  client/src/common/Header.js
  client/src/style/GreetingInfo.js
  client/src/style/HeaderStyle.js
Labels: 💻 FE, 🖌 Design

#229 [FE][Design][Fix] 헤더 반응형웹, 로그아웃시 메인으로 이동
  client/src/common/Header.js
  client/src/style/HeaderStyle.js
Labels: 💻 FE, 🖌 Design, ✔ Fix

#230 [Feat][FE]refreshToken으로 accessToken 자동갱신, Mypage_img삽입
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/page/community/Board.js
  client/src/page/community/Community.js
  client/src/page/user/Mypage.js
  client/src/redux/MypageSlice.js
  client/src/style/MyStyle.js
  client/src/utils/api.js
  client/src/utils/cookie.js
Labels: 💻 FE, 🕹 Feat

#231 [FE][Fix] API_SERVER주소 변경
  a4e53ea87526328d6410b56d9d695f7718d0e57471c7e938099e18e3d66c.jpg
  client/.env
  client/.env.dev
  client/src/page/search/SearchResult.js
  client/src/page/survey/Survey.js
  client/src/page/user/KakaoLogin.js
  client/src/page/user/Login.js
  client/src/page/user/LoginModal.js
  client/src/page/user/Signup.js
  ddea4358c16e07d5417fd91644d7af7f4e543f7829205b0f649d0617dd42.png
Labels: 💻 FE, ✔ Fix

#232 [FE][Fix] git ignore, webpack.yml 파일 주소변경
  .github/workflows/webpack.yml
  client/src/common/GoogleSearch.js
  client/src/page/survey/SurveyStep/Step3.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, ✔ Fix

#233 [Fix][FE] env 배포후 코드 수정
  client/.env
  client/.env.dev
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/s3/client/CustomS3Client.java
  server/src/main/resources/application.yml
Labels: 💻 FE, ✔ Fix

#234 [FE][Fix] 로그아웃 Navigate > useNavigate
  client/src/common/Header.js
Labels: 💻 FE, ✔ Fix

#235 [FE][Fix] 헤더 로그아웃, post 버그 수정
  client/src/common/Header.js
  client/src/style/HeaderStyle.js
Labels: 💻 FE, ✔ Fix

#236 [FE][Feat]설문에서 아무것도 선택안할시 alert기능 추가
  client/src/common/GoogleSearch.js
  client/src/page/survey/Survey.js
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step2.js
  client/src/page/survey/SurveyStep/Step3.js
Labels: 💻 FE, 🕹 Feat

#237 [FE][Fix] 자동완성 문자열 방식 수정
  client/src/common/GoogleSearch.js
Labels: 💻 FE, ✔ Fix

#238 [FE][Fix] secrets 위한 yml에서 .env파일 생성
  .github/workflows/webpack.yml
  client/src/common/GoogleSearch.js
  client/src/utils/api.js
Labels: 💻 FE, ✔ Fix

#239 [FE][Fix] secrets 위한 yml에서 .env파일 생성2
  client/src/common/GoogleSearch.js
Labels: 💻 FE, ✔ Fix

#240 [BE][Refactor] 인프라 리빌딩으로 인한 코드 수정
  server/src/main/java/com/codestates/sebmainproject009/auth/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/sebmainproject009/s3/client/CustomS3Client.java
  server/src/main/resources/application.yml
Labels: 💻 BE, 🛠 Refactor

#243 [Refactor] 인프라 리빌딩으로 인한 코드 수정
  .github/workflows/gradle.yml
  .github/workflows/webpack.yml
Labels: 🛠 Refactor

#244 [Refactor] 인프라 리빌딩으로 인한 코드 수정
  .github/workflows/webpack.yml
  server/src/main/java/com/codestates/sebmainproject009/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
Labels: 🛠 Refactor

#245 [FE][Fix] 구글 자동완성 src적용
  client/src/common/GoogleSearch.js
Labels: 💻 FE, ✔ Fix

#246 [Fix][FE]board height 추가
  client/src/style/BoardStyle.js
  client/src/utils/api.js
Labels: 💻 FE, ✔ Fix

#248 [FE][Fix] favicon 경로 index.html수정
  client/src/index.html
Labels: 💻 FE, ✔ Fix

#249 [Fix][FE] mypage 버그수정
  client/src/page/user/Mypage.js
  client/src/style/BoardStyle.js
Labels: 💻 FE, ✔ Fix

#250 [Fix][FE]mypage수정
  client/src/page/user/Mypage.js
Labels: ✔ Fix

#251 [FE][Design][Refactor] searchlist 목록 pointer 수정 및 중복코드 제거
  client/src/page/search/Searchlist.js
  client/src/style/SearchStyle.js
Labels: 💻 FE, 🖌 Design, 🛠 Refactor

#252 [Fix]header logout시 새로고침
  client/src/page/user/Mypage.js
Labels: ✔ Fix

#253 [FE][Design] SurveyStep 버튼크기 반응형웹 수정
  client/src/page/survey/SurveyStep/Step4.js
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🖌 Design

#254 [FE][Design] SurveyStep 버튼크기 반응형웹 수정2
  client/src/style/SurveyStyle.js
Labels: 💻 FE, 🖌 Design

#255 [Fix]Mypage 버그수 정
  client/src/common/Header.js
  client/src/page/user/Mypage.js
Labels: ✔ Fix

#256 [FE][Fix] 맞춤추천다시하기 구글자동완성초기화를 위한 새로고침코드추가
  client/src/page/survey/SurveyStep/Step1.js
  client/src/page/survey/SurveyStep/Step3.js
Labels: 💻 FE, ✔ Fix

#258 [BE][Refactor] User 엔티티 수정
  .github/workflows/gradle.yml
  README.md
  server/src/main/java/com/codestates/sebmainproject009/auth/userdetails/UserDetailsService.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/mapper/CommuMapper.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
Labels: 💻 BE, 🛠 Refactor

#259 [BE][Refactor] User 엔티티 수정
  README.md
  server/src/main/java/com/codestates/sebmainproject009/auth/userdetails/UserDetailsService.java
  server/src/main/java/com/codestates/sebmainproject009/commu/controller/CommuController.java
  server/src/main/java/com/codestates/sebmainproject009/commu/dto/CommuResponseDto.java
  server/src/main/java/com/codestates/sebmainproject009/commu/mapper/CommuMapper.java
  server/src/main/java/com/codestates/sebmainproject009/search/controller/SearchController.java
  server/src/main/java/com/codestates/sebmainproject009/user/entity/User.java
  server/src/main/java/com/codestates/sebmainproject009/user/service/UserService.java
Labels: 💻 BE, 🛠 Refactor
